### ISSUE TITLE
Languages not consistent.

### ISSUE THREAD

**Issue by kpcenti** [setsumi/pfreepanic#2]
UI is in English while voice is not spoken in English,

**Comment by setsumi** [comment]
Well, rationale behind this was as follows:
- Tool itself is intended to be run in the background and what you actually using/playing is the game itself inherently entirely in Japanese, so English voice would be weird.
- Even without Japanese knowledge it's easy to understand because "Premium Free Mode" is pronounced in English anyway, although with an accent.
- Voice sound files are included with the tool and have obvious names, so you can play them in media player to understand better.
- Or just replace them with your own sounds.

**Comment by kpcenti** [comment]
The app is still in English. It's still inconsistent.

**Comment by setsumi** [comment]
Okay, added English voices.
