### ISSUE TITLE
Help adapting to pfree museca?

### ISSUE THREAD

**Issue by camprevail** [setsumi/pfreepanic#3]
I tried to adapt the pfree code to Museca (which is 64 bit), but I keep getting 
`ERROR:
Read process memory failed
299: Only part of a ReadProcessMemory or WriteProcessMemory request was completed.`

I plugged in the offset, the dll name and the window name, and compiled it for 64bit, but idk I've just been struggling with it for hours now lol. Maybe you could take a stab at it? The only hex that needs to be toggled is: 
`Offset: 0x17E587
off: 0XFF, 0X83, 0X48, 0X14, 0X00, 0X00
on: 0X90, 0X90, 0X90, 0X90, 0X90, 0X90`

**Comment by setsumi** [comment]
Here's how I've done it with sdvx.
Illustration pictures: https://imgur.com/a/cxo3YMJ
1. run the game
2. run the debugger (i.e. x64dbg) and attach it to the game process
3. go to Memory Map tab and locate your dll (museca.dll?)
4. pick Find Pattern and paste long pfree hex code without 0x prefixes
5. should find it inside the Executable code section of your dll
Now, dll patch offsets starts from zero, but in the memory dll is placed not on the zero address but on some another (base address) you see on the above picture. Therefore to make it zero take found code address (011a7866) and subtract base address (01010000), result is 197866. Looks similar to dll offsets
```
ULONG data0_offset[] = { 0x1CEE4F, 0x196BDF };
ULONG data1_offset[] = { 0x1CF016, 0x196C66 };
```
but not the same because dll format in memory is different from disk file. And here magic number is used to fix the difference.
`#define MEM_OFFSET  0xC00 // offset padding relative to .dll file`

Pfreepanic works the same way
1. finds the dll base address
```
			MODULEINFO info;
			if (!GetModuleInformation(hProc, hMods[i], &info, sizeof(MODULEINFO))) {
...
				baseAddr = (ULONG)info.lpBaseOfDll;
```
2. reads the memory from (base address + dll offset + magic number)
`	if (!ReadProcessMemory(hProc, (BYTE*)baseAddr + MEM_OFFSET + data0_offset[Game], &data0, 1, NULL)) {`
So I suggest looking at those values, compare them with the debugger and correct the discrepancy by adjusting magic number.

I don't know anything about 64 bit stuff (using Windows XP 32 bit here) so there may be some issues unique to it, or not. But at least I think you should replace `ULONG` in the code with `unsigned long long` because `ULONG` is 32 bit and can't hold 64 bit addresses so they become corrupted.

**Comment by camprevail** [comment]
Thanks for the info! How do I calculate the MEM_OFFSET from the base address?

**Comment by setsumi** [comment]
If program works in general and address to read (sum of three values) is valid inside that code section and not corrupted or weird, then at least reading should succeed returning some code relatively nearby. Just search for this code in debugger and see the difference from where target code is located.

**Comment by camprevail** [comment]
Well I got further thanks to your guidance! I commented out all the data1 code since it seemed to be interfering. I subtracted the offset address from the base address in a hex calculator. 
Now I'm getting some interesting output in the pfreepanic text box, it changes every few times I hit the assigned key. Something like:

```FF
00 00 12754E66 14D84C 01 5541A0 14F9C0 2DE8500 3F81430 2DE1340 2DFE460 1F0680 01 28A0021 51 BE06B0
```

So I switched to the other `sprintf` code you had in there below `// find our module and get base address` and got this:

```C:\WINDOWS\SYSTEM32\WINNSI.DLL		 0x0B7F0000		 0x0000B000		 0x0B7F1DB0```

Should that be not be museca.dll? I updated the code I'm using in my fork if you could take a glance at it for me. https://github.com/camprevail/pfreepanic/blob/master/Unit1.cpp

**Comment by setsumi** [comment]
Ugh, you are printing only `data0` one byte variable, but requesting 17 values inside quotes, this is syntax violation.
About printing module and base address, it must be done right after `baseAddr` assignment and before `break;` because `break` jumps out of there entirely, so your print looks like previous checked module and not actually used one.

Can I ask what do you used to compile this for 64bit? I'm kind of curious and may try to do something.

**Comment by camprevail** [comment]
Haha sorry, I'm no good with code but I'm trying. I used radstudio C++ builder 64bit.

**Comment by setsumi** [comment]
Try this
https://github.com/setsumi/pfreepanic64/releases

**Comment by camprevail** [comment]
Sick! It works great, on pc and the cab! (which runs win7 embedded). Museca seems to take total control of the audio card, unlike voltex, so it's unable to play the wav files, but that's no biggie.  I'll have to figure out a way to build a switch or some kind of visual on/off notification for the cab, or maybe implement a hardware switch instead of a keyboard key. Also, I uncommented `PROCESS_ALL_ACCESS` and rebuilt so it automatically runs with elevated privileges. Otherwise, it throws that error. 
But seriously, thank you so much for your time and knowledge, I appreciate the help immensely. Are you on any of the rhythm game discords?

**Comment by setsumi** [comment]
Glad it worked on actual game! I got curious and wanted to play with new C++Builder, so.
About sound issue had this suspicion too. In theory it is possible to make an OSD like message, but that involves real hackery (injecting dll, hook DirectX and drawing by myself), a bit too much research needed.
`PROCESS_ALL_ACCESS` bit is strange, works for me without it. Oh well.
I'm technically on most of common discords, but mostly hang on "enigmatic" one.

**Comment by camprevail** [comment]
That's my hangout as well. You'll find me as Cammy there!
